-- Create fight_outcomes table for tracking battle predictions vs actual results
-- Run this in Supabase SQL editor to set up the table

CREATE TABLE IF NOT EXISTS fight_outcomes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Teams (JSON arrays of { hero_id, bp_contribution })
  team_player JSONB NOT NULL,
  team_enemy JSONB NOT NULL,
  
  -- Battle Power
  bp_player INTEGER NOT NULL DEFAULT 0,
  bp_enemy INTEGER NOT NULL DEFAULT 0,
  
  -- Outcome
  winner TEXT NOT NULL CHECK (winner IN ('player', 'enemy')),
  
  -- Prediction (stored for accuracy analysis)
  predicted_win_rate NUMERIC(5,2),
  
  -- Battle context
  mode TEXT DEFAULT 'pvp',
  notes TEXT,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Indexes for filtering and aggregation
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE INDEX idx_fight_outcomes_user_id ON fight_outcomes(user_id);
CREATE INDEX idx_fight_outcomes_created_at ON fight_outcomes(created_at);
CREATE INDEX idx_fight_outcomes_winner ON fight_outcomes(winner);

-- Enable RLS
ALTER TABLE fight_outcomes ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only view/insert their own fight outcomes
CREATE POLICY "Users can view own fight outcomes"
  ON fight_outcomes FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own fight outcomes"
  ON fight_outcomes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Grant permissions
GRANT SELECT, INSERT ON fight_outcomes TO authenticated;
GRANT SELECT ON fight_outcomes TO anon;
